---
name: Check ðŸ› 

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
      - codespaces_conf

# This reusable workflow from insightsengineering/r.pkg.template will run once a PR to main branch is created.
jobs:
  job-setup:
    name: Should we run R CMD check?
    runs-on: ubuntu-latest
    outputs:
      check_out: ${{ steps.check.outputs.run_r_cmd_check }}
    steps:
      - name: To check or not to check?
        id: check
        run: |
          echo "run_r_cmd_check=false" >> $GITHUB_OUTPUT

  r-cmd:
    name: R CMD Check ðŸ§¬
    needs: job-setup
    # Call a workflow from a given GitHub repository, from a given branch (or tag).
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    if: >
      needs.job-setup.outputs.check_out == 'true'

  job-setup-with-docker:
    name: Should we run R CMD check?
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/user-workshop-cicd/r-pkg-example:4.3"

    steps:
      - name: Running R CMD Check using r-pkg-example:4.3 image
        run: |
          R CMD check
